export const DOCUMENT_INDEX_CONFIG = {
  model: "nvidia/nemotron-3-embed-1b:free",
  responseModels: ["nvidia/nemotron-3-embed-1b:free", "nvidia/nemotron-3-embed-1b", "private/openrouter/nvidia/nemotron-3-embed-1b"] as readonly string[],
  tokenizer: "nemotron-3-embed-1b",
  endpoint: "https://openrouter.ai/api/v1/embeddings",
  dimensions: 2048,
  contextTokens: 32_768,
  maxTokens: 384,
  overlapTokens: 64,
  batchSize: 32,
  batchCharacters: 48_000,
  requestTimeoutMs: 60_000,
  requestIntervalMs: 3_500,
  maxResponseBytes: 8_000_000,
  charactersPerPage: 3_000,
  maxFileBytes: 2_000_000,
  maxCorpusCharacters: 4_000_000,
  databasePath: "data/documents.sqlite",
  reportPath: "data/documents-comparison.json",
  runLockPath: "data/documents-index.lock",
  chunkPageSize: 20,
} as const;
